criteria_explanation = {
    "Economic Feasibility": "Search the document for details about financial considerations relevant to factory location selection. This includes costs related to land acquisition, construction, utilities, and workforce. Look for mentions of tax policies, government incentives, subsidies, or economic support programs that could influence the feasibility of a location.",
    "Infrastructure and Accessibility": "Identify and extract information on infrastructure and accessibility. Focus on transportation networks such as proximity to highways, ports, railroads, and airports. Include any details about utilities like electricity, water, waste management, and digital infrastructure (e.g., broadband availability). Highlight aspects that facilitate efficient operations at the proposed location.",
    "Environmental Sustainability": "Locate sections discussing environmental considerations. Include mentions of compliance with environmental regulations, renewable energy opportunities, waste management practices, and any initiatives to minimize ecological impact. Focus on how these factors align with sustainability goals or potential risks posed by the location.",
    "Labor Market and Workforce": "Search for information on workforce availability and characteristics. Include discussions on labor pool size, skill levels, education, and training opportunities. Look for demographic trends, workforce adaptability, and any potential challenges or advantages related to hiring and retaining staff in the area.",
    "Proximity and Logistics": "Find references to logistical factors influencing location selection. Include information about proximity to suppliers, customers, and distribution networks. Highlight any logistical advantages such as reduced transportation times or costs, and details about the integration with existing supply chains or networks.",
    "Legal and Political" : "Extract details on the legal and political environment impacting factory location decisions. Look for mentions of regulatory requirements, ease of business setup, trade policies, and intellectual property protections. Include references to political stability, risk factors, or any local policies that might affect operations.",
    "Growth and Scalability" : "Identify sections addressing growth and scalability potential. Look for mentions of land availability for expansion, zoning regulations, and flexibility for adapting to future needs. Include discussions about market trends or conditions that might support long-term growth and scalability at the location.",
    "Innovation and Technological Ecosystem" : "Look for mentions of innovation or technological opportunities in the document. Include references to research institutions, technology clusters, or partnerships that could support innovation. Identify any mention of advanced manufacturing technologies, Industry 4.0 capabilities, or automation that may enhance factory operations.",
}